name: Postman API Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'postman/**'
      - '.github/workflows/postman.yml'

jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Start ServeRest
        run: npx serverest@latest &
      - name: Wait API
        run: sleep 10
      - name: Run Newman
        run: npm run test:postman
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: newman-report
          path: postman/reports/
